apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  app-name: {{ .Values.app.name }}
  app-port: "{{ .Values.app.port }}"
  db-host: {{ .Values.database.host }}
  db-port: "{{ .Values.database.port }}"